/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import parcial2017.Verificacion2;




/**
 *
 * @author Damian
 */
public class alfa extends javax.swing.JFrame {

    /**
     * Creates new form alfa
     */
    public alfa() {
        
               
        initComponents();
        this.setSize(800, 600);
        this.setLocationRelativeTo(null);
        
         String abecedario="ABCDEFGHIJKLMNÑOPQRSTUVWXYZ";
            
            List<String> chars = Arrays.asList(abecedario.split(""));
            
            Collections.shuffle(chars);
            String salida = "";
           
            for (String s : chars) {
             salida += s;
            }
            
             List<String> grupos = Arrays.asList(salida.split("(?<=\\G.{3})"));
             
            System.out.println(grupos);
            
            tbtn1.setText(grupos.get(0));
            tbtn2.setText(grupos.get(1));
            tbtn3.setText(grupos.get(2));
            tbtn4.setText(grupos.get(3));
            tbtn5.setText(grupos.get(4));
            tbtn6.setText(grupos.get(5));
            
            
            if (grupos.get(1).contains("A")) {
                System.out.println("ESAAAAAAAAAA");
            } else {
            }

        
        
                
    }

    public JButton getBtnConfirma() {
        return btnConfirma;
    }

    public void setBtnConfirma(JButton btnConfirma) {
        this.btnConfirma = btnConfirma;
    }

    public JButton getBtnVolver() {
        return btnVolver;
    }

    public void setBtnVolver(JButton btnVolver) {
        this.btnVolver = btnVolver;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JToggleButton getTbtn1() {
        return tbtn1;
    }

    public void setTbtn1(JToggleButton tbtn1) {
        this.tbtn1 = tbtn1;
    }

    public JToggleButton getTbtn2() {
        return tbtn2;
    }

    public void setTbtn2(JToggleButton tbtn2) {
        this.tbtn2 = tbtn2;
    }

    public JToggleButton getTbtn3() {
        return tbtn3;
    }

    public void setTbtn3(JToggleButton tbtn3) {
        this.tbtn3 = tbtn3;
    }

    public JToggleButton getTbtn4() {
        return tbtn4;
    }

    public void setTbtn4(JToggleButton tbtn4) {
        this.tbtn4 = tbtn4;
    }

    public JToggleButton getTbtn5() {
        return tbtn5;
    }

    public void setTbtn5(JToggleButton tbtn5) {
        this.tbtn5 = tbtn5;
    }

    public JToggleButton getTbtn6() {
        return tbtn6;
    }

    public void setTbtn6(JToggleButton tbtn6) {
        this.tbtn6 = tbtn6;
    }


  




    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnConfirma = new javax.swing.JButton();
        tbtn1 = new javax.swing.JToggleButton();
        tbtn2 = new javax.swing.JToggleButton();
        tbtn3 = new javax.swing.JToggleButton();
        tbtn4 = new javax.swing.JToggleButton();
        tbtn5 = new javax.swing.JToggleButton();
        tbtn6 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONFIRMACION ALFA");
        setBackground(new java.awt.Color(0, 0, 204));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Seleccione donde aparecen las letras elegidas en el orden correspondiente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 430, 13);

        btnVolver.setBackground(new java.awt.Color(255, 51, 51));
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver);
        btnVolver.setBounds(50, 220, 100, 23);

        btnConfirma.setBackground(new java.awt.Color(0, 204, 102));
        btnConfirma.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirma.setText("Confirmar");
        getContentPane().add(btnConfirma);
        btnConfirma.setBounds(200, 220, 100, 23);

        tbtn1.setBackground(new java.awt.Color(0, 0, 204));
        tbtn1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tbtn1.setForeground(new java.awt.Color(255, 255, 0));
        tbtn1.setText("jToggleButton1");
        tbtn1.setBorder(null);
        tbtn1.setOpaque(true);
        getContentPane().add(tbtn1);
        tbtn1.setBounds(50, 50, 87, 15);

        tbtn2.setBackground(new java.awt.Color(0, 0, 204));
        tbtn2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tbtn2.setForeground(new java.awt.Color(255, 255, 0));
        tbtn2.setText("jToggleButton2");
        tbtn2.setBorder(null);
        getContentPane().add(tbtn2);
        tbtn2.setBounds(50, 100, 87, 15);

        tbtn3.setBackground(new java.awt.Color(0, 0, 204));
        tbtn3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tbtn3.setForeground(new java.awt.Color(255, 255, 0));
        tbtn3.setText("jToggleButton3");
        tbtn3.setBorder(null);
        getContentPane().add(tbtn3);
        tbtn3.setBounds(50, 150, 87, 15);

        tbtn4.setBackground(new java.awt.Color(0, 0, 204));
        tbtn4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tbtn4.setForeground(new java.awt.Color(255, 255, 0));
        tbtn4.setText("jToggleButton4");
        tbtn4.setBorder(null);
        getContentPane().add(tbtn4);
        tbtn4.setBounds(200, 50, 87, 15);

        tbtn5.setBackground(new java.awt.Color(0, 0, 204));
        tbtn5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tbtn5.setForeground(new java.awt.Color(255, 255, 0));
        tbtn5.setText("jToggleButton5");
        tbtn5.setBorder(null);
        getContentPane().add(tbtn5);
        tbtn5.setBounds(200, 100, 87, 15);

        tbtn6.setBackground(new java.awt.Color(0, 0, 204));
        tbtn6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tbtn6.setForeground(new java.awt.Color(255, 255, 0));
        tbtn6.setText("jToggleButton6");
        tbtn6.setBorder(null);
        getContentPane().add(tbtn6);
        tbtn6.setBounds(200, 150, 87, 15);

        jLabel2.setBackground(new java.awt.Color(0, 0, 204));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirma;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton tbtn1;
    private javax.swing.JToggleButton tbtn2;
    private javax.swing.JToggleButton tbtn3;
    private javax.swing.JToggleButton tbtn4;
    private javax.swing.JToggleButton tbtn5;
    private javax.swing.JToggleButton tbtn6;
    // End of variables declaration//GEN-END:variables

    
    public static void letraAleatoria2() {
                   
           
           
        }

}


